import org.jetbrains.kotlin.gradle.dsl.KotlinVersion

plugins {
    id 'com.android.library'
    id 'com.vanniktech.maven.publish'
}

android {
    namespace = 'com.lazygeniouz.acv'
    compileSdk = 35

    defaultConfig {
        minSdk = 24
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

kotlin {
    compilerOptions {
        languageVersion = KotlinVersion.KOTLIN_1_9
        apiVersion = KotlinVersion.KOTLIN_1_9
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.lifecycle:lifecycle-runtime:2.10.0'
    api 'com.google.android.libraries.ads.mobile.sdk:ads-mobile-sdk:1.3.1'
}