plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.lazygeniouz.acv.example'
    compileSdk = 37

    defaultConfig {
        minSdk = 24
        targetSdk = 37

        versionCode = 1
        versionName = '1.0'
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    implementation project(':acv')

    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.activity:activity-ktx:1.13.0'
    implementation 'com.google.android.material:material:1.14.0'
}