import org.jetbrains.kotlin.gradle.dsl.KotlinVersion

plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'com.vanniktech.maven.publish'
}

android {
    namespace = 'com.lazygeniouz.acv.compose'
    compileSdk = 37

    defaultConfig {
        minSdk = 24
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    buildFeatures {
        compose = true
    }
}

kotlin {
    compilerOptions {
        apiVersion = KotlinVersion.KOTLIN_2_2
        languageVersion = KotlinVersion.KOTLIN_2_2
    }
}

dependencies {
    api project(':acv')
    api 'androidx.compose.ui:ui:1.12.1'
    implementation 'androidx.compose.foundation:foundation-layout:1.12.1'
}

mavenPublishing {
    coordinates(GROUP, 'acv-compose', VERSION_NAME)

    pom {
        name = 'AdContainerView Compose'
        description = 'Jetpack Compose support for AdContainerView.'
    }
}